[mypy]
python_version = 3.11
files = backend/main.py, backend/analytics.py
ignore_missing_imports = True
follow_imports = silent
warn_return_any = False
no_implicit_optional = False
check_untyped_defs = False
warn_unused_ignores = False
warn_redundant_casts = False
disable_error_code = import-untyped,unused-ignore,assignment,var-annotated

[mypy-backend.main]
allow_redefinition = True

[mypy-backend.analytics]
allow_redefinition = True
