import { defineConfig, loadEnv, type Plugin } from 'vite';
import react from '@vitejs/plugin-react-swc';
import tailwindcss from '@tailwindcss/vite';
import path from 'path';

const CSS_PROBE_ENV = 'VITE_CSS_TIMING_PROBE';
const CSS_PROBE_THRESHOLD_MS = 25;

const isCssResource = (id: string) => /\.(css|pcss|postcss|scss|sass|less|styl|stylus)(?:$|\?)/.test(id);

const normalizeIdForLog = (id: string) => {
  const withoutQuery = id.split('?')[0] ?? id;
  return withoutQuery.replace(/\\/g, '/');
};

const createCssTimingProbePlugins = (): Plugin[] => {
  if (process.env[CSS_PROBE_ENV] !== '1') {
    return [];
  }

  const cssProbePlugin: Plugin = {
    name: 'mathpulse-css-probe',
    apply: 'serve',
    configureServer(server) {
      const originalTransformRequest = server.transformRequest.bind(server);
      server.transformRequest = (async (url, options) => {
        const target = String(url);
        if (!isCssResource(target)) {
          return originalTransformRequest(url, options);
        }

        const transformStart = performance.now();
        try {
          return await originalTransformRequest(url, options);
        } finally {
          const transformDuration = performance.now() - transformStart;
          if (transformDuration >= CSS_PROBE_THRESHOLD_MS) {
            // Timing log only when CSS_PROBE_THRESHOLD_MS is exceeded
          }
        }
      }) as typeof server.transformRequest;

      const pluginContainer = server.pluginContainer as {
        transform: (code: string, id: string, options?: unknown) => Promise<unknown>;
      };
      const originalPluginTransform = pluginContainer.transform.bind(pluginContainer);
      pluginContainer.transform = (async (code, id, options) => {
        if (!isCssResource(id)) {
          return originalPluginTransform(code, id, options);
        }

        const transformStart = performance.now();
        try {
          return await originalPluginTransform(code, id, options);
        } finally {
          const transformDuration = performance.now() - transformStart;
          if (transformDuration >= CSS_PROBE_THRESHOLD_MS) {
            // Timing log only when CSS_PROBE_THRESHOLD_MS is exceeded
          }
        }
      }) as typeof pluginContainer.transform;

      server.middlewares.use((req, res, next) => {
        const url = req.url?.split('?')[0] ?? '';
        if (!url.endsWith('.css')) {
          next();
          return;
        }

        const requestStart = performance.now();
        res.on('finish', () => {
          const duration = performance.now() - requestStart;
          if (duration >= CSS_PROBE_THRESHOLD_MS) {
            // Timing log only when CSS_PROBE_THRESHOLD_MS is exceeded
          }
        });

        next();
      });
    },
  };

  return [cssProbePlugin];
};

const cssTimingProbePlugins = createCssTimingProbePlugins();

/**
 * Generates `/firebase-config.js` (consumed by `public/firebase-messaging-sw.js`)
 * by reading `VITE_FIREBASE_*` values from the loaded env. Runs in dev (served
 * via middleware) and in build (emitted as a static asset).
 *
 * Why a separate file: the FCM service worker cannot read `import.meta.env`,
 * and we don't want to hardcode keys in the SW source. This plugin keeps the
 * config in one place (the Vite env) while still making it available to the SW.
 */
const fcmConfigPlugin = (): Plugin => {
  const ENDPOINT = '/firebase-config.js';
  let envSnapshot: Record<string, string> = {};

  const buildScript = (env: Record<string, string>) => {
    const safe = (v: string | undefined) =>
      JSON.stringify(typeof v === 'string' ? v : '');
    return [
      '// Auto-generated by mathpulse-fcm-config (vite.config.ts).',
      '// Read by /firebase-messaging-sw.js to initialise FCM in the SW context.',
      `self.FIREBASE_API_KEY = ${safe(env.VITE_FIREBASE_API_KEY)};`,
      `self.FIREBASE_AUTH_DOMAIN = ${safe(env.VITE_FIREBASE_AUTH_DOMAIN)};`,
      `self.FIREBASE_PROJECT_ID = ${safe(env.VITE_FIREBASE_PROJECT_ID)};`,
      `self.FIREBASE_STORAGE_BUCKET = ${safe(env.VITE_FIREBASE_STORAGE_BUCKET)};`,
      `self.FIREBASE_MESSAGING_SENDER_ID = ${safe(env.VITE_FIREBASE_MESSAGING_SENDER_ID)};`,
      `self.FIREBASE_APP_ID = ${safe(env.VITE_FIREBASE_APP_ID)};`,
      '',
    ].join('\n');
  };

  return {
    name: 'mathpulse-fcm-config',
    config(_userConfig, configEnv) {
      // Vite calls this hook before resolving the final config. We use
      // loadEnv() so .env / .env.local / .env.production values are picked
      // up exactly the same way the client bundle sees them.
      envSnapshot = loadEnv(configEnv.mode, process.cwd(), 'VITE_');
    },
    configureServer(server) {
      server.middlewares.use(ENDPOINT, (_req, res) => {
        res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
        res.setHeader('Cache-Control', 'no-cache');
        res.end(buildScript(envSnapshot));
      });
    },
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'firebase-config.js',
        source: buildScript(envSnapshot),
      });
    },
  };
};

export default defineConfig({
  plugins: [...cssTimingProbePlugins, react(), tailwindcss(), fcmConfigPlugin()],
  optimizeDeps: {
    include: [
      'firebase/app',
      'firebase/auth',
      'firebase/firestore',
      'firebase/storage',
      'firebase/analytics',
      'firebase/database',
      'firebase/functions',
      '@tanstack/react-query',
      'motion/react',
      'lucide-react',
      'sonner',
      'recharts',
      'zod',
      'react-hook-form',
      'class-variance-authority',
      '@radix-ui/react-slot',
      'date-fns',
      'clsx',
    ],
  },
  resolve: {
    extensions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  build: {
    target: 'esnext',
    outDir: 'build',
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (!id.includes('node_modules')) {
            return undefined;
          }

          if (
            id.includes('react-markdown') ||
            id.includes('remark-math') ||
            id.includes('rehype-katex') ||
            id.includes('katex')
          ) {
            return 'vendor-markdown';
          }

          if (/node_modules\/(react|react-dom|scheduler)\//.test(id)) {
            return 'vendor-react';
          }

          if (/node_modules\/(?:firebase|@firebase)\/auth/.test(id)) {
            return 'vendor-firebase-auth';
          }

          if (/node_modules\/(?:firebase|@firebase)\/firestore/.test(id)) {
            return 'vendor-firebase-firestore';
          }

          if (/node_modules\/(?:firebase|@firebase)\/storage/.test(id)) {
            return 'vendor-firebase-storage';
          }

          if (/node_modules\/(?:firebase|@firebase)\/analytics/.test(id)) {
            return 'vendor-firebase-analytics';
          }

          if (id.includes('firebase') || id.includes('@firebase')) {
            return 'vendor-firebase-core';
          }

          if (id.includes('@radix-ui')) {
            return 'vendor-radix';
          }

          if (id.includes('recharts')) {
            return 'vendor-charts';
          }

          if (id.includes('xlsx') || id.includes('xlsx/')) {
            return 'vendor-xlsx';
          }

          return undefined;
        },
      },
    },
  },
  server: {
    // Force IPv4 loopback. On Windows 10/11 with Hyper-V Host Network Service
    // running (Docker Desktop / WSL2 / virtualization), the OS reserves random
    // ports in the 1024–14999 dynamic range, hidden from
    // `netsh int ipv4 show excludedportrange`. Vite's default `localhost` host
    // resolves to `::1` first → EACCES on `::1:3000` even when no process
    // listens. Binding to `127.0.0.1` sidesteps the IPv6 reservation; the
    // explicit port choice (5173) sits above the HNS dynamic pool ceiling
    // (~15000) so it is never silently reserved by the kernel.
    //
    // Recovery if 3000 is reservation-blocked again: see DEV_SERVER.md or run
    // (in elevated PowerShell): `net stop winnat && net start winnat`.
    host: '127.0.0.1',
    port: 5173,
    strictPort: false,
    open: false,
    warmup: {
      clientFiles: [
        './src/main.tsx',
        './src/App.tsx',
        './src/contexts/AuthContext.tsx',
        './src/contexts/ChatContext.tsx',
        './src/components/DashboardAvatar.tsx',
        './src/components/ui/utils.ts',
        './src/types/models.ts',
        './src/lib/firebase.ts',
        './src/services/apiService.ts',
        './src/data/subjects.ts',
        './src/components/Sidebar.tsx',
        './src/components/TeacherDashboard.tsx',
      ],
    },
    fs: {
      allow: ['.', './node_modules/.vite', './node_modules'],
    },
    hmr: {
      overlay: false,
    },
    cacheDir: 'node_modules/.vite',
  },
});