// PDF Generator Service
// Uses browser's built-in print functionality for PDF generation

import { Student, RiskLevel, Module } from '../types';

interface StudentReport {
  student: Student;
  recommendations: string[];
  weakAreas: string[];
  strengthAreas: string[];
}

interface ClassSummary {
  totalStudents: number;
  avgScore: number;
  avgEngagement: number;
  riskDistribution: { high: number; medium: number; low: number };
  topWeakTopics: string[];
}

// Generate HTML content for printing
export const pdfGenerator = {
  // Generate Student Progress Report HTML
  generateStudentProgressReport(students: Student[]): string {
    const date = new Date().toLocaleDateString();
    
    const studentRows = students.map(student => {
      const riskColor = student.riskLevel === RiskLevel.HIGH ? '#ef4444' : 
                        student.riskLevel === RiskLevel.MEDIUM ? '#f59e0b' : '#10b981';
      return `
        <tr>
          <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">${student.name}</td>
          <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">
            <span style="background: ${riskColor}20; color: ${riskColor}; padding: 4px 12px; border-radius: 9999px; font-size: 12px;">
              ${student.riskLevel}
            </span>
          </td>
          <td style="padding: 12px; border-bottom: 1px solid #e2e8f0; text-align: center;">${student.avgQuizScore}%</td>
          <td style="padding: 12px; border-bottom: 1px solid #e2e8f0; text-align: center;">${student.engagementScore}%</td>
          <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">${student.weakestTopic}</td>
        </tr>
      `;
    }).join('');

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Student Progress Report - MathPulse AI</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; max-width: 1000px; margin: 0 auto; }
          h1 { color: #0ea5e9; margin-bottom: 8px; }
          .subtitle { color: #64748b; margin-bottom: 24px; }
          table { width: 100%; border-collapse: collapse; margin-top: 24px; }
          th { background: #f8fafc; padding: 12px; text-align: left; border-bottom: 2px solid #e2e8f0; color: #475569; font-weight: 600; }
          .summary-cards { display: flex; gap: 16px; margin-bottom: 32px; }
          .card { flex: 1; background: #f8fafc; padding: 16px; border-radius: 8px; text-align: center; }
          .card-value { font-size: 32px; font-weight: bold; color: #0ea5e9; }
          .card-label { color: #64748b; font-size: 14px; margin-top: 4px; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <h1>📊 Student Progress Report</h1>
        <p class="subtitle">Generated on ${date} by MathPulse AI</p>
        
        <div class="summary-cards">
          <div class="card">
            <div class="card-value">${students.length}</div>
            <div class="card-label">Total Students</div>
          </div>
          <div class="card">
            <div class="card-value">${Math.round(students.reduce((a, s) => a + s.avgQuizScore, 0) / students.length)}%</div>
            <div class="card-label">Class Average</div>
          </div>
          <div class="card">
            <div class="card-value" style="color: #ef4444;">${students.filter(s => s.riskLevel === RiskLevel.HIGH).length}</div>
            <div class="card-label">At-Risk Students</div>
          </div>
        </div>
        
        <table>
          <thead>
            <tr>
              <th>Student Name</th>
              <th>Risk Level</th>
              <th>Quiz Average</th>
              <th>Engagement</th>
              <th>Focus Area</th>
            </tr>
          </thead>
          <tbody>
            ${studentRows}
          </tbody>
        </table>
        
        <p style="margin-top: 32px; color: #64748b; font-size: 12px; text-align: center;">
          This report was automatically generated by MathPulse AI • Confidential
        </p>
      </body>
      </html>
    `;
  },

  // Generate Remedial Worksheets HTML
  generateRemedialWorksheets(students: Student[]): string {
    const date = new Date().toLocaleDateString();
    
    // Group students by weak topic
    const topicGroups: Record<string, Student[]> = {};
    students.forEach(student => {
      if (!topicGroups[student.weakestTopic]) {
        topicGroups[student.weakestTopic] = [];
      }
      topicGroups[student.weakestTopic].push(student);
    });

    // Generate practice problems for common topics
    const worksheetProblems: Record<string, string[]> = {
      'Calculus - Derivatives': [
        '1. Find the derivative of f(x) = 3x² + 2x - 5',
        '2. Find the derivative of f(x) = sin(x) + cos(x)',
        '3. Use the chain rule to find dy/dx where y = (2x + 1)³',
        '4. Find f\'(x) where f(x) = x³ · e^x',
        '5. Calculate the derivative of f(x) = ln(x² + 1)'
      ],
      'Algebra - Quadratic Equations': [
        '1. Solve: x² - 5x + 6 = 0',
        '2. Find the roots of 2x² + 7x - 15 = 0',
        '3. Complete the square: x² + 8x + c = 0',
        '4. Graph y = x² - 4x + 3 and identify the vertex',
        '5. Solve using the quadratic formula: 3x² - 2x - 8 = 0'
      ],
      'Trigonometry - Unit Circle': [
        '1. Find sin(π/4) and cos(π/4)',
        '2. Convert 270° to radians',
        '3. Find all angles θ where sin(θ) = 1/2',
        '4. Evaluate tan(π/3)',
        '5. Find the exact value of cos(5π/6)'
      ],
      'Statistics - Standard Deviation': [
        '1. Calculate the mean of: 12, 15, 18, 22, 23',
        '2. Find the variance of: 4, 6, 8, 10, 12',
        '3. Calculate the standard deviation of: 5, 7, 9, 11, 13',
        '4. A dataset has σ = 3.5 and μ = 10. What does this tell us?',
        '5. Compare the spread of two datasets using their standard deviations'
      ]
    };

    const topicSections = Object.entries(topicGroups).map(([topic, studentsInTopic]) => {
      const problems = worksheetProblems[topic] || [
        '1. Review the fundamental concepts',
        '2. Practice basic problems',
        '3. Work through intermediate examples',
        '4. Attempt challenging applications',
        '5. Complete the review questions'
      ];
      
      return `
        <div class="worksheet-section">
          <h2>📝 ${topic}</h2>
          <p class="students-list">Recommended for: ${studentsInTopic.map(s => s.name).join(', ')}</p>
          
          <div class="problems">
            ${problems.map(p => `<div class="problem">${p}</div>`).join('')}
          </div>
          
          <div class="answer-space">
            <p><strong>Show your work:</strong></p>
            <div class="lines">
              ${Array(10).fill('<div class="line"></div>').join('')}
            </div>
          </div>
        </div>
      `;
    }).join('<div class="page-break"></div>');

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Remedial Worksheets - MathPulse AI</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
          h1 { color: #0ea5e9; margin-bottom: 8px; }
          h2 { color: #475569; margin-top: 32px; border-bottom: 2px solid #0ea5e9; padding-bottom: 8px; }
          .subtitle { color: #64748b; margin-bottom: 24px; }
          .students-list { background: #f0f9ff; padding: 12px; border-radius: 8px; color: #0369a1; font-size: 14px; }
          .problems { margin: 24px 0; }
          .problem { padding: 16px; background: #f8fafc; border-left: 4px solid #0ea5e9; margin-bottom: 12px; font-size: 16px; }
          .answer-space { margin-top: 24px; }
          .lines { margin-top: 12px; }
          .line { height: 32px; border-bottom: 1px solid #cbd5e1; margin-bottom: 8px; }
          .page-break { page-break-after: always; }
          .worksheet-section { margin-bottom: 48px; }
          @media print { 
            body { padding: 20px; }
            .page-break { page-break-after: always; }
          }
        </style>
      </head>
      <body>
        <h1>📚 Remedial Worksheets</h1>
        <p class="subtitle">Generated on ${date} by MathPulse AI • Personalized Practice Problems</p>
        
        ${topicSections}
        
        <p style="margin-top: 32px; color: #64748b; font-size: 12px; text-align: center;">
          Generated by MathPulse AI based on individual student performance data
        </p>
      </body>
      </html>
    `;
  },

  // Generate Class Performance Summary HTML
  generateClassSummary(students: Student[]): string {
    const date = new Date().toLocaleDateString();
    const avgScore = Math.round(students.reduce((a, s) => a + s.avgQuizScore, 0) / students.length);
    const avgEngagement = Math.round(students.reduce((a, s) => a + s.engagementScore, 0) / students.length);
    
    const highRisk = students.filter(s => s.riskLevel === RiskLevel.HIGH).length;
    const mediumRisk = students.filter(s => s.riskLevel === RiskLevel.MEDIUM).length;
    const lowRisk = students.filter(s => s.riskLevel === RiskLevel.LOW).length;
    
    // Count weak topics
    const topicCounts: Record<string, number> = {};
    students.forEach(s => {
      topicCounts[s.weakestTopic] = (topicCounts[s.weakestTopic] || 0) + 1;
    });
    const topWeakTopics = Object.entries(topicCounts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5);

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Class Performance Summary - MathPulse AI</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; max-width: 900px; margin: 0 auto; }
          h1 { color: #0ea5e9; margin-bottom: 8px; }
          h2 { color: #475569; margin-top: 32px; }
          .subtitle { color: #64748b; margin-bottom: 32px; }
          .stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 32px; }
          .stat-card { background: linear-gradient(135deg, #0ea5e9, #0284c7); color: white; padding: 24px; border-radius: 12px; text-align: center; }
          .stat-card.warning { background: linear-gradient(135deg, #f59e0b, #d97706); }
          .stat-card.success { background: linear-gradient(135deg, #10b981, #059669); }
          .stat-value { font-size: 36px; font-weight: bold; }
          .stat-label { font-size: 14px; opacity: 0.9; margin-top: 4px; }
          .risk-distribution { display: flex; gap: 8px; margin: 24px 0; }
          .risk-bar { height: 32px; border-radius: 4px; display: flex; align-items: center; justify-content: center; color: white; font-weight: 600; }
          .risk-bar.high { background: #ef4444; }
          .risk-bar.medium { background: #f59e0b; }
          .risk-bar.low { background: #10b981; }
          .topic-list { list-style: none; padding: 0; }
          .topic-item { display: flex; justify-content: space-between; padding: 12px 16px; background: #f8fafc; margin-bottom: 8px; border-radius: 8px; }
          .topic-count { background: #0ea5e9; color: white; padding: 4px 12px; border-radius: 9999px; font-size: 14px; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <h1>📈 Class Performance Summary</h1>
        <p class="subtitle">Generated on ${date} by MathPulse AI</p>
        
        <div class="stats-grid">
          <div class="stat-card">
            <div class="stat-value">${students.length}</div>
            <div class="stat-label">Total Students</div>
          </div>
          <div class="stat-card success">
            <div class="stat-value">${avgScore}%</div>
            <div class="stat-label">Class Average</div>
          </div>
          <div class="stat-card">
            <div class="stat-value">${avgEngagement}%</div>
            <div class="stat-label">Avg Engagement</div>
          </div>
          <div class="stat-card warning">
            <div class="stat-value">${highRisk}</div>
            <div class="stat-label">At-Risk Students</div>
          </div>
        </div>
        
        <h2>Risk Distribution</h2>
        <div class="risk-distribution">
          <div class="risk-bar high" style="flex: ${highRisk};">${highRisk} High</div>
          <div class="risk-bar medium" style="flex: ${mediumRisk};">${mediumRisk} Medium</div>
          <div class="risk-bar low" style="flex: ${lowRisk};">${lowRisk} Low</div>
        </div>
        
        <h2>Most Challenging Topics</h2>
        <ul class="topic-list">
          ${topWeakTopics.map(([topic, count]) => `
            <li class="topic-item">
              <span>${topic}</span>
              <span class="topic-count">${count} students</span>
            </li>
          `).join('')}
        </ul>
        
        <h2>Recommendations</h2>
        <ul style="line-height: 2;">
          <li>Focus remediation efforts on the top challenging topics</li>
          <li>Provide additional support for the ${highRisk} high-risk students</li>
          <li>Consider peer tutoring between low-risk and high-risk students</li>
          <li>Schedule review sessions for topics with multiple struggling students</li>
        </ul>
        
        <p style="margin-top: 32px; color: #64748b; font-size: 12px; text-align: center;">
          This report was automatically generated by MathPulse AI • Confidential
        </p>
      </body>
      </html>
    `;
  },

  // Generate Study Guides HTML
  generateStudyGuides(topics: string[]): string {
    const date = new Date().toLocaleDateString();
    
    const studyContent: Record<string, { overview: string; keyPoints: string[]; examples: string[] }> = {
      'Calculus - Derivatives': {
        overview: 'Derivatives measure the rate of change of a function. They are fundamental to understanding motion, optimization, and many real-world applications.',
        keyPoints: [
          'The derivative of f(x) is written as f\'(x) or df/dx',
          'Power Rule: d/dx[xⁿ] = nxⁿ⁻¹',
          'Product Rule: d/dx[f·g] = f\'g + fg\'',
          'Chain Rule: d/dx[f(g(x))] = f\'(g(x))·g\'(x)',
          'The derivative represents the slope of the tangent line'
        ],
        examples: [
          'd/dx[x³] = 3x²',
          'd/dx[sin(x)] = cos(x)',
          'd/dx[e^x] = e^x',
          'd/dx[ln(x)] = 1/x'
        ]
      },
      'Algebra - Quadratic Equations': {
        overview: 'Quadratic equations are polynomial equations of degree 2, with the general form ax² + bx + c = 0.',
        keyPoints: [
          'Standard form: ax² + bx + c = 0',
          'Quadratic formula: x = (-b ± √(b²-4ac)) / 2a',
          'Discriminant (b²-4ac) determines the number of solutions',
          'Vertex form: a(x-h)² + k where (h,k) is the vertex',
          'Factoring: Look for two numbers that multiply to ac and add to b'
        ],
        examples: [
          'x² - 5x + 6 = 0 → (x-2)(x-3) = 0 → x = 2, 3',
          '2x² + 4x - 6 = 0 → x = 1, -3',
          'x² + 4 = 0 → No real solutions (discriminant < 0)'
        ]
      },
      'Trigonometry - Unit Circle': {
        overview: 'The unit circle is a circle with radius 1 centered at the origin. It provides a geometric interpretation of trigonometric functions.',
        keyPoints: [
          'Key angles: 0°, 30°, 45°, 60°, 90° (and their radian equivalents)',
          'sin(θ) = y-coordinate on unit circle',
          'cos(θ) = x-coordinate on unit circle',
          'tan(θ) = sin(θ)/cos(θ)',
          'Pythagorean identity: sin²(θ) + cos²(θ) = 1'
        ],
        examples: [
          'sin(π/6) = 1/2, cos(π/6) = √3/2',
          'sin(π/4) = √2/2, cos(π/4) = √2/2',
          'sin(π/2) = 1, cos(π/2) = 0'
        ]
      }
    };

    const defaultContent = {
      overview: 'This topic covers fundamental mathematical concepts that are essential for advanced studies.',
      keyPoints: [
        'Understand the basic definitions and terminology',
        'Practice solving various problem types',
        'Apply concepts to real-world scenarios',
        'Review common mistakes and how to avoid them',
        'Connect this topic to related mathematical concepts'
      ],
      examples: [
        'Work through textbook examples',
        'Complete practice problem sets',
        'Review class notes and examples'
      ]
    };

    const guideSections = topics.map(topic => {
      const content = studyContent[topic] || defaultContent;
      
      return `
        <div class="guide-section">
          <h2>📖 ${topic}</h2>
          
          <div class="overview">
            <h3>Overview</h3>
            <p>${content.overview}</p>
          </div>
          
          <div class="key-points">
            <h3>Key Points to Remember</h3>
            <ul>
              ${content.keyPoints.map(p => `<li>${p}</li>`).join('')}
            </ul>
          </div>
          
          <div class="examples">
            <h3>Examples</h3>
            <ul>
              ${content.examples.map(e => `<li class="example">${e}</li>`).join('')}
            </ul>
          </div>
          
          <div class="practice-box">
            <h3>Practice Tips</h3>
            <ul>
              <li>Start with simple problems and gradually increase difficulty</li>
              <li>Write out each step of your solution</li>
              <li>Check your answers and understand any mistakes</li>
              <li>Practice regularly for at least 20 minutes per day</li>
            </ul>
          </div>
        </div>
      `;
    }).join('<div class="page-break"></div>');

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Study Guides - MathPulse AI</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
          h1 { color: #0ea5e9; margin-bottom: 8px; }
          h2 { color: #0ea5e9; margin-top: 32px; border-bottom: 2px solid #0ea5e9; padding-bottom: 8px; }
          h3 { color: #475569; margin-top: 24px; }
          .subtitle { color: #64748b; margin-bottom: 32px; }
          .overview { background: #f0f9ff; padding: 16px; border-radius: 8px; margin: 16px 0; }
          .overview p { color: #0369a1; margin: 0; line-height: 1.6; }
          ul { line-height: 2; }
          .example { font-family: 'Courier New', monospace; background: #f8fafc; padding: 8px; border-radius: 4px; }
          .practice-box { background: #fef3c7; padding: 16px; border-radius: 8px; margin-top: 24px; }
          .practice-box h3 { color: #92400e; margin-top: 0; }
          .practice-box ul { margin-bottom: 0; }
          .page-break { page-break-after: always; }
          .guide-section { margin-bottom: 48px; }
          @media print { 
            body { padding: 20px; }
            .page-break { page-break-after: always; }
          }
        </style>
      </head>
      <body>
        <h1>📚 Topic Study Guides</h1>
        <p class="subtitle">Generated on ${date} by MathPulse AI</p>
        
        ${guideSections}
        
        <p style="margin-top: 32px; color: #64748b; font-size: 12px; text-align: center;">
          Generated by MathPulse AI • For educational use
        </p>
      </body>
      </html>
    `;
  },

  // Open print dialog with generated HTML
  printDocument(html: string, title: string) {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.document.title = title;
      
      // Wait for content to load then trigger print
      printWindow.onload = () => {
        setTimeout(() => {
          printWindow.print();
        }, 250);
      };
    }
  },

  // Download as HTML file (can be opened in Word for DOCX)
  downloadAsFile(html: string, filename: string, format: 'pdf' | 'docx') {
    if (format === 'docx') {
      // Create downloadable HTML file (opens in Word)
      const blob = new Blob([html], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${filename}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } else {
      // For PDF, open print dialog
      this.printDocument(html, filename);
    }
  }
};

export default pdfGenerator;
