export interface GradesPdfSubjectRow {
  readonly subject: string;
  readonly average: number;
}

export interface GradesPdfQuizRow {
  readonly title: string;
  readonly subject: string;
  readonly score: number;
  readonly date: string;
  readonly type: string;
  readonly status: string;
}

export interface GradesPdfOptions {
  readonly studentName: string;
  readonly exportDate: string;
  readonly subjectFilter: string;
  readonly typeFilter: string;
  readonly subjectRows: readonly GradesPdfSubjectRow[];
  readonly quizRows: readonly GradesPdfQuizRow[];
}

type PdfCellValue = string | number;

export async function createGradesPdf(options: GradesPdfOptions): Promise<Blob> {
  const [{ jsPDF }, { autoTable }] = await Promise.all([import('jspdf'), import('jspdf-autotable')]);
  const doc = Object.assign(new jsPDF(), { lastAutoTable: { finalY: 0 } });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  const footerHeight = 12;
  let cursorY = 48;

  const checkPage = (neededHeight: number): void => {
    if (cursorY + neededHeight > pageHeight - footerHeight) {
      doc.addPage();
      cursorY = 20;
    }
  };

  const writeWrapped = (text: string, indent = 0): void => {
    const lines = doc.splitTextToSize(text, contentWidth - indent);
    for (const line of lines) {
      checkPage(5);
      doc.text(line, margin + indent, cursorY);
      cursorY += 5;
    }
  };

  const drawTable = (headers: readonly string[], rows: readonly PdfCellValue[][]): void => {
    autoTable(doc, {
      head: [Array.from(headers)],
      body: rows.map((row) => Array.from(row)),
      startY: cursorY,
      margin: { left: margin, right: margin, bottom: footerHeight },
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 2.5, overflow: 'linebreak' },
      headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255] },
    });
    cursorY = doc.lastAutoTable.finalY + 10;
  };

  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageWidth, 38, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('MathPulse AI', margin, 16);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Grade Report', margin, 24);
  doc.setFontSize(9);
  doc.text(`Generated: ${options.exportDate}`, margin, 32);
  doc.setTextColor(0, 0, 0);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Student:', margin, cursorY);
  doc.setFont('helvetica', 'normal');
  writeWrapped(options.studentName, 42);
  writeWrapped(`Subject Filter: ${options.subjectFilter}`);
  writeWrapped(`Type Filter: ${options.typeFilter}`);
  cursorY += 5;

  if (options.subjectRows.length === 0 && options.quizRows.length === 0) {
    checkPage(8);
    doc.setFont('helvetica', 'italic');
    writeWrapped('No grade data available for the selected filters.');
  } else {
    if (options.subjectRows.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.text('Subject Performance', margin, cursorY);
      cursorY += 6;
      drawTable(
        ['Subject', 'Average Score'],
        options.subjectRows.map((row) => [row.subject, row.average]),
      );
    }

    if (options.quizRows.length > 0) {
      checkPage(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Recent Quizzes', margin, cursorY);
      cursorY += 6;
      drawTable(
        ['Title', 'Subject', 'Score', 'Date', 'Type', 'Status'],
        options.quizRows.map((row) => [
          row.title,
          row.subject,
          row.score,
          row.date,
          row.type,
          row.status,
        ]),
      );
    }
  }

  const totalPages = doc.getNumberOfPages();
  for (let pageNumber = 1; pageNumber <= totalPages; pageNumber += 1) {
    doc.setPage(pageNumber);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by MathPulse AI', margin, pageHeight - 8);
    const pageLabel = `Page ${pageNumber} of ${totalPages}`;
    doc.text(pageLabel, pageWidth - margin - doc.getTextWidth(pageLabel), pageHeight - 8);
  }

  return new Blob([doc.output('arraybuffer')], { type: 'application/pdf' });
}
