/**
 * MathPulse AI Cloud Functions - Quiz Processor
 *
 * Handles quiz submission events: recalculates per-subject risk,
 * merges into user profile, and builds remedial quiz configs.
 */

import * as admin from "firebase-admin";
import * as functions from "firebase-functions";
import {
  AT_RISK_THRESHOLD,
  REMEDIAL_CONFIG,
  DEFAULT_BLOOM_LEVELS,
  DEFAULT_QUESTION_TYPES,
  NOTIFICATION_TYPES,
  REMEDIAL_QUIZ_DUE_DAYS,
} from "../config/constants";
import { createNotification } from "./notificationSender";

// ─── Types ────────────────────────────────────────────────────

export interface QuizSubmissionData {
  lrn: string;
  quizId: string;
  subject: string;
  score: number;
  totalQuestions: number;
  correctAnswers: number;
  timeSpentSeconds: number;
  answers?: any[];
}

export interface RemedialQuizConfig {
  lrn: string;
  subject: string;
  quizConfig: {
    topics: string[];
    gradeLevel: string;
    numQuestions: number;
    questionTypes: string[];
    difficultyDistribution: { easy: number; medium: number; hard: number };
    bloomLevels: string[];
    includeGraphs: boolean;
    excludeTopics: string[];
    purpose: string;
    targetLrn: string;
  };
  status: string;
  autoGenerated: boolean;
  reason: string;
  priority: string;
  dueInDays: number;
}

// ─── Quiz Submission Processor ────────────────────────────────

/**
 * Process a quiz submission: recalculate risk for the submitted subject,
 * merge into the student's profile, and notify if status changed.
 */
export async function processQuizSubmission(
  data: QuizSubmissionData,
): Promise<void> {
  const { lrn, subject, score, quizId } = data;
  const db = admin.firestore();

  functions.logger.info("[QUIZ] Processing quiz submission", {
    lrn,
    subject,
    score,
    quizId,
  });

  // Determine new status for this subject
  const newStatus = score < AT_RISK_THRESHOLD ? "At Risk" : "On Track";
  const confidence = newStatus === "At Risk"
    ? Math.round(((AT_RISK_THRESHOLD - score) / AT_RISK_THRESHOLD) * 100) / 100
    : Math.round(((score - AT_RISK_THRESHOLD) / (100 - AT_RISK_THRESHOLD)) * 100) / 100;

  const newClassification = {
    status: newStatus,
    score,
    confidence: Math.abs(confidence),
    needsIntervention: newStatus === "At Risk",
  };

  // Fetch current student profile
  const userRef = db.collection("users").doc(lrn);
  const userSnap = await userRef.get();

  if (!userSnap.exists) {
    functions.logger.warn("Student profile not found", { lrn });
    return;
  }

  const userData = userSnap.data()!;
  const existingBadges: Record<string, string> = userData.subjectBadges || {};
  const existingClassifications: Record<string, any> = userData.riskClassifications || {};
  const existingAtRisk: string[] = userData.atRiskSubjects || [];
  const previousStatus = existingClassifications[subject]?.status;

  // Merge
  const updatedBadges = { ...existingBadges, [subject]: newStatus };
  const updatedClassifications = {
    ...existingClassifications,
    [subject]: newClassification,
  };
  let updatedAtRisk = [...existingAtRisk];

  if (newStatus === "At Risk" && !updatedAtRisk.includes(subject)) {
    updatedAtRisk.push(subject);
  } else if (newStatus === "On Track") {
    updatedAtRisk = updatedAtRisk.filter((s) => s !== subject);
  }

  await userRef.update({
    subjectBadges: updatedBadges,
    riskClassifications: updatedClassifications,
    atRiskSubjects: updatedAtRisk,
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  });

  // Notify if status changed
  if (previousStatus && previousStatus !== newStatus) {
    const direction = newStatus === "At Risk" ? "dropped to" : "improved to";
    await createNotification({
      userId: lrn,
      type: NOTIFICATION_TYPES.GRADE,
      title: `${subject} Status Changed`,
      message: `Your ${subject} status ${direction} ${newStatus} after scoring ${score}%.`,
    });

    functions.logger.info("Status change detected", {
      lrn,
      subject,
      from: previousStatus,
      to: newStatus,
    });
  }

  functions.logger.info("[OK] Quiz submission processed", { lrn, subject, newStatus });
}

// ─── Build Remedial Quiz Configs ─────────────────────────────

/**
 * Build quiz configuration objects for remedial assignments.
 * Ready to be written to the `assignedQuizzes` collection.
 */
export function buildRemedialQuizConfigs(
  lrn: string,
  atRiskSubjects: string[],
  overallRisk: string,
  gradeLevel: string,
): RemedialQuizConfig[] {
  const cfg = REMEDIAL_CONFIG[overallRisk] || REMEDIAL_CONFIG.Low;
  const quizzes: RemedialQuizConfig[] = [];

  for (const subject of atRiskSubjects) {
    quizzes.push({
      lrn,
      subject,
      quizConfig: {
        topics: [subject],
        gradeLevel,
        numQuestions: cfg.questions,
        questionTypes: DEFAULT_QUESTION_TYPES,
        difficultyDistribution: cfg.dist,
        bloomLevels: DEFAULT_BLOOM_LEVELS,
        includeGraphs: false,
        excludeTopics: [],
        purpose: "remedial",
        targetLrn: lrn,
      },
      status: "pending",
      autoGenerated: true,
      reason: `Diagnostic identified "${subject}" as At Risk`,
      priority: overallRisk === "High" ? "high" : "medium",
      dueInDays: REMEDIAL_QUIZ_DUE_DAYS,
    });
  }

  return quizzes;
}
